steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['run', 'build-ci']
  env:
    - 'PATH_PREFIX=$SHORT_SHA'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'public', 'gs://staging.nodejs.dev/$SHORT_SHA']
